### ISSUE TITLE
failed to register layer: Error processing tar file(exit status 1): remount /, flags: 0x84000: invalid argument

### ISSUE THREAD

**Issue by Federico2014** [mahajanvv/EHRUsingBlockchain#1]
I get the following proble where I run  ./downloadFabric.sh, do you  know what is the problem, can you help solve it ?

zp@DESKTOP-K30SJ3Q:~/projects/EHRUsingBlockchain$ ./downloadFabric.sh
Development only script for Hyperledger Fabric control
Running 'downloadFabric.sh'
FABRIC_VERSION is unset, assuming hlfv12
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)
1.2.1: Pulling from hyperledger/fabric-peer
b234f539f7a1: Extracting [==================================================>]  43.12MB/43.12MB
55172d420b43: Download complete
5ba5bbeb6b91: Download complete
43ae2841ad7a: Download complete
f6c9c6de4190: Download complete
c6af77e36488: Download complete
964f7f4f22f3: Download complete
6c2a3b5ab78f: Download complete
56bf6b50282b: Download complete
aa6c5a3c5275: Download complete
failed to register layer: Error processing tar file(exit status 1): remount /, flags: 0x84000: invalid argument

**Comment by mahajanvv** [comment]
Sorry for late response i will get back to u soon
